command_timeout = 1000

[directory]
truncation_length = 4
truncate_to_repo = false

[git_branch]
symbol = "git:"

[git_status]
ahead = "ahead ${count}"
behind = "behind ${count}"
diverged = "diverged ${ahead_count}/${behind_count}"
